In [37]:
import pandas as pd
import numpy as np

In [38]:
df_taxis_fuel= pd.read_csv("Vehicle Fuel Economy Data.csv")

C:\Users\Mati Barna\AppData\Local\Temp\ipykernel_11872\753944670.py:1: DtypeWarning: Columns (73,75) have mixed types. Specify dtype option on import or set low_memory=False.
  df_taxis_fuel= pd.read_csv("Vehicle Fuel Economy Data.csv")

In [39]:
df_taxis_fuel.head(2)

,Year,Manufacturer,Model,barrels08,barrelsA08,charge240,city08,city08U,cityA08,cityA08U,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,2017,BMW,M6 Coupe,17.500588,0.0,0.0,15.0,14.0,0.0,0.0,...,BMX,NaN,0.0,NaN,04-04-2016,09-09-2016,Y,0.0,0.0,0.0
1,2017,BMW,X3 sDrive28i,12.396250,0.0,0.0,21.0,21.0,0.0,0.0,...,BMX,NaN,0.0,NaN,04-04-2016,22-11-2016,Y,0.0,0.0,0.0

In [40]:
# Revisamos la composiciÃ³n del mismo
df_taxis_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46186 entries, 0 to 46185
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             46186 non-null  int64
 1   Manufacturer     46186 non-null  object
 2   Model            46176 non-null  object
 3   barrels08        46169 non-null  float64
 4   barrelsA08       46169 non-null  float64
 5   charge240        46169 non-null  float64
 6   city08           46169 non-null  float64
 7   city08U          46169 non-null  float64
 8   cityA08          46169 non-null  float64
 9   cityA08U         46169 non-null  float64
 10  cityCD           46169 non-null  float64
 11  cityE            46169 non-null  float64
 12  cityUF           46169 non-null  float64
 13  co2              46169 non-null  float64
 14  co2A             46169 non-null  float64
 15  co2TailpipeAGpm  46169 non-null  float64
 16  co2TailpipeGpm   46169 non-null  float64
 17  comb08           46169 non-null  float64
 18  comb08U          46169 non-null  float64
 19  combA08          46169 non-null  float64
 20  combA08U         46169 non-null  float64
 21  combE            46169 non-null  float64
 22  combinedCD       46169 non-null  float64
 23  combinedUF       46169 non-null  float64
 24  cylinders        45663 non-null  float64
 25  displ            45665 non-null  float64
 26  drive            44983 non-null  object
 27  engId            46169 non-null  float64
 28  eng_dscr         29092 non-null  object
 29  feScore          44953 non-null  float64
 30  fuelCost08       44953 non-null  float64
 31  fuelCostA08      44953 non-null  float64
 32  fuelType         44953 non-null  object
 33  fuelType1        44953 non-null  object
 34  ghgScore         44953 non-null  float64
 35  ghgScoreA        44953 non-null  float64
 36  highway08        44953 non-null  float64
 37  highway08U       44953 non-null  float64
 38  highwayA08       44953 non-null  float64
 39  highwayA08U      44953 non-null  float64
 40  VClass           44953 non-null  object
 41  highwayCD        44192 non-null  float64
 42  highwayE         44192 non-null  float64
 43  highwayUF        44192 non-null  float64
 44  hlv              44192 non-null  float64
 45  hpv              44192 non-null  float64
 46  id               44192 non-null  float64
 47  lv2              44192 non-null  float64
 48  lv4              44192 non-null  float64
 49  mpgData          44179 non-null  object
 50  phevBlended      44192 non-null  object
 51  pv2              44192 non-null  float64
 52  pv4              44192 non-null  float64
 53  range            44192 non-null  float64
 54  rangeCity        44192 non-null  float64
 55  rangeCityA       44192 non-null  float64
 56  rangeHwy         44192 non-null  float64
 57  rangeHwyA        44192 non-null  float64
 58  trany            44181 non-null  object
 59  UCity            44192 non-null  float64
 60  UCityA           44192 non-null  float64
 61  UHighway         44192 non-null  float64
 62  UHighwayA        44192 non-null  float64
 63  youSaveSpend     44192 non-null  float64
 64  guzzler          2635 non-null   object
 65  trans_dscr       14391 non-null  object
 66  tCharger         8531 non-null   object
 67  sCharger         987 non-null    object
 68  atvType          4386 non-null   object
 69  fuelType2        1647 non-null   object
 70  rangeA           1642 non-null   object
 71  evMotor          1874 non-null   object
 72  mfrCode          15200 non-null  object
 73  c240Dscr         133 non-null    object
 74  charge240b       44170 non-null  float64
 75  c240bDscr        127 non-null    object
 76  createdOn        44170 non-null  object
 77  modifiedOn       44170 non-null  object
 78  startStop        14357 non-null  object
 79  phevCity         44170 non-null  float64
 80  phevHwy          44170 non-null  float64
 81  phevComb         44170 non-null  float64
dtypes: float64(57), int64(1), object(24)
memory usage: 28.9+ MB

In [41]:
# Revisamos las columnas
df_taxis_fuel.columns

Index(['Year', 'Manufacturer', 'Model', 'barrels08', 'barrelsA08', 'charge240',
       'city08', 'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF',
       'co2', 'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'VClass',
       'highwayCD', 'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4',
       'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'youSaveSpend', 'guzzler', 'trans_dscr',
       'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA', 'evMotor',
       'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr', 'createdOn',
       'modifiedOn', 'startStop', 'phevCity', 'phevHwy', 'phevComb'],
      dtype='object')

In [42]:
df_taxis_fuel.fuelType.unique()

array(['Premium', 'Regular', 'Diesel', 'Electricity', 'Gasoline or E85',
       'Midgrade', 'Premium and Electricity', 'Premium or E85', nan,
       'Regular Gas and Electricity', 'Regular Gas or Electricity',
       'Premium Gas or Electricity', 'CNG', 'Gasoline or natural gas',
       'Gasoline or propane'], dtype=object)

In [43]:
df_taxis_fuel.fuelType1.unique()

array(['Premium Gasoline', 'Regular Gasoline', 'Diesel', 'Electricity',
       'Midgrade Gasoline', nan, 'Natural Gas'], dtype=object)

In [44]:
df_taxis_fuel.fuelType2.unique()

array([nan, 'E85', 'Electricity', 'Natural Gas', 'Propane'], dtype=object)

In [45]:
# Se eliminan las columas que no vamos a usar
eliminar = ['barrelsA08','charge240','fuelType','barrels08','range',
       'city08U','cityA08','cityA08U','cityCD','cityE','cityUF',
       'city08', 'comb08U','combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF',
       'cylinders','displ', 'drive', 'engId', 'eng_dscr', 'fuelCostA08', 'ghgScoreA',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U',
       'highwayCD', 'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4',
       'mpgData', 'phevBlended', 'pv2', 'pv4','rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCityA',
       'UHighway', 'UHighwayA', 'guzzler', 'trans_dscr',
       'tCharger', 'sCharger', 'atvType', 'evMotor','rangeA',
       'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr',
        'startStop', 'phevCity', 'phevHwy', 'phevComb','VClass']
df_taxis_fuel = df_taxis_fuel.drop(eliminar, axis=1)
df_taxis_fuel.head(2)

,Year,Manufacturer,Model,co2,comb08,feScore,fuelCost08,fuelType1,ghgScore,UCity,youSaveSpend,fuelType2,createdOn,modifiedOn
0,2017,BMW,M6 Coupe,519.0,17.0,3.0,3850.0,Premium Gasoline,3.0,17.9989,-9750.0,NaN,04-04-2016,09-09-2016
1,2017,BMW,X3 sDrive28i,374.0,24.0,5.0,2700.0,Premium Gasoline,5.0,26.7866,-4000.0,NaN,04-04-2016,22-11-2016

In [46]:
# Se renombran las columnas 
df_taxis_fuel.rename(columns={'comb08':'Miles per gallon (mpg)','co2':'CO2 (p/mile)','fuelType1':'Fuel',
                             'fuelType2':'Alternative Fuel', 'feScore': 'ef_x_comb', 'fuelCost08':'comb_x_year',
                             'ghgScore':'score_ghg','UCity': 'ef_x_comb_city'}, inplace=True)

In [47]:
df_taxis_fuel.head(2)

,Year,Manufacturer,Model,CO2 (p/mile),Miles per gallon (mpg),ef_x_comb,comb_x_year,Fuel,score_ghg,ef_x_comb_city,youSaveSpend,Alternative Fuel,createdOn,modifiedOn
0,2017,BMW,M6 Coupe,519.0,17.0,3.0,3850.0,Premium Gasoline,3.0,17.9989,-9750.0,NaN,04-04-2016,09-09-2016
1,2017,BMW,X3 sDrive28i,374.0,24.0,5.0,2700.0,Premium Gasoline,5.0,26.7866,-4000.0,NaN,04-04-2016,22-11-2016

# Diccionario de Datos

- **Year:** AÃ±o de fabricaciÃ³n del vehÃ­culo.
- **Manufacturer:** Marca del vehÃ­culo.
- **Model:** Modelo del vehÃ­culo.
- **CO2 (p/mile):** Emisiones de CO2 por milla.
- **Miles per gallon (mpg):** Consumo de combustible en millas por galÃ³n.
- **ef_x_comb:** PuntuaciÃ³n de eficiencia del vehÃ­culo por combustible.
- **comb_x_year:** Gasto estimado de combustible por aÃ±o.
- **Fuel:** Tipo de combustible utilizado por el vehÃ­culo.
- **score_ghg:** PuntuaciÃ³n de emisiones de gases de efecto invernadero (GHG) por vehÃ­culo (Cuanto mayor sea la puntuaciÃ³n, menos emisiones de gases de efecto invernadero emitirÃ¡ el vehÃ­culo.).
- **ef_x_comb_city:** Eficiencia de combustible en condiciones de conducciÃ³n en la ciudad.
- **youSaveSpend:** Indica cuÃ¡nto se puede ahorrar o gastar en combustible en comparaciÃ³n con un vehÃ­culo promedio.
- **Alternative Fuel:** Tipo de combustible alternativo que puede utilizar.
- **createdOn:** Indica la fecha de creaciÃ³n de los registros en el conjunto de datos.
- **modifiedOn:** Indica la fecha de modificaciÃ³n de los registros en el conjunto de datos.

In [48]:
df_taxis_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46186 entries, 0 to 46185
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    46186 non-null  int64
 1   Manufacturer            46186 non-null  object
 2   Model                   46176 non-null  object
 3   CO2 (p/mile)            46169 non-null  float64
 4   Miles per gallon (mpg)  46169 non-null  float64
 5   ef_x_comb               44953 non-null  float64
 6   comb_x_year             44953 non-null  float64
 7   Fuel                    44953 non-null  object
 8   score_ghg               44953 non-null  float64
 9   ef_x_comb_city          44192 non-null  float64
 10  youSaveSpend            44192 non-null  float64
 11  Alternative Fuel        1647 non-null   object
 12  createdOn               44170 non-null  object
 13  modifiedOn              44170 non-null  object
dtypes: float64(7), int64(1), object(6)
memory usage: 4.9+ MB

In [49]:
# Se cuentan cuantos nulos hay por columna
df_taxis_fuel.isnull().sum()

Year                          0
Manufacturer                  0
Model                        10
CO2 (p/mile)                 17
Miles per gallon (mpg)       17
ef_x_comb                  1233
comb_x_year                1233
Fuel                       1233
score_ghg                  1233
ef_x_comb_city             1994
youSaveSpend               1994
Alternative Fuel          44539
createdOn                  2016
modifiedOn                 2016
dtype: int64

In [50]:
# Se eliminan las filas donde 'Fuel' es nulo
df_taxis_fuel = df_taxis_fuel[df_taxis_fuel['Fuel'].notna()]
df_taxis_fuel.head(2)

,Year,Manufacturer,Model,CO2 (p/mile),Miles per gallon (mpg),ef_x_comb,comb_x_year,Fuel,score_ghg,ef_x_comb_city,youSaveSpend,Alternative Fuel,createdOn,modifiedOn
0,2017,BMW,M6 Coupe,519.0,17.0,3.0,3850.0,Premium Gasoline,3.0,17.9989,-9750.0,NaN,04-04-2016,09-09-2016
1,2017,BMW,X3 sDrive28i,374.0,24.0,5.0,2700.0,Premium Gasoline,5.0,26.7866,-4000.0,NaN,04-04-2016,22-11-2016

In [51]:
# Completamos los valores nulos de la columna 'Alternative Fuel' con 'No', ya que se trata de los vehiculos no hibridos.
df_taxis_fuel['Alternative Fuel'] = df_taxis_fuel['Alternative Fuel'].fillna('No')
df_taxis_fuel.head(2)

,Year,Manufacturer,Model,CO2 (p/mile),Miles per gallon (mpg),ef_x_comb,comb_x_year,Fuel,score_ghg,ef_x_comb_city,youSaveSpend,Alternative Fuel,createdOn,modifiedOn
0,2017,BMW,M6 Coupe,519.0,17.0,3.0,3850.0,Premium Gasoline,3.0,17.9989,-9750.0,No,04-04-2016,09-09-2016
1,2017,BMW,X3 sDrive28i,374.0,24.0,5.0,2700.0,Premium Gasoline,5.0,26.7866,-4000.0,No,04-04-2016,22-11-2016

In [52]:
# Se revisan duplicados
duplicados= df_taxis_fuel.duplicated().sum()
print(f'cantidad de datos duplicados {duplicados}')

cantidad de datos duplicados 2140

In [53]:
# Se eliminan las filas con duplicados
df_taxis_fuel = df_taxis_fuel.drop_duplicates()
duplicados= df_taxis_fuel.duplicated().sum()
print(f'cantidad de datos duplicados {duplicados}')

cantidad de datos duplicados 0

In [54]:
df_taxis_fuel

,Year,Manufacturer,Model,CO2 (p/mile),Miles per gallon (mpg),ef_x_comb,comb_x_year,Fuel,score_ghg,ef_x_comb_city,youSaveSpend,Alternative Fuel,createdOn,modifiedOn
0,2017,BMW,M6 Coupe,519.0,17.0,3.0,3850.0,Premium Gasoline,3.0,17.9989,-9750.0,No,04-04-2016,09-09-2016
1,2017,BMW,X3 sDrive28i,374.0,24.0,5.0,2700.0,Premium Gasoline,5.0,26.7866,-4000.0,No,04-04-2016,22-11-2016
2,2016,Infiniti,Q50S Red Sport,402.0,22.0,5.0,2950.0,Premium Gasoline,5.0,25.1000,-5250.0,No,04-04-2016,26-09-2016
3,2017,MINI,John Cooper Works Convertible,327.0,27.0,6.0,2400.0,Premium Gasoline,6.0,30.8534,-2500.0,No,12-04-2016,16-09-2016
4,2017,Kia,Sedona SX,433.0,21.0,4.0,2550.0,Regular Gasoline,4.0,22.8000,-3250.0,No,12-04-2016,02-12-2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46177,1993,Mitsubishi,Diamante,-1.0,18.0,-1.0,3650.0,Premium Gasoline,-1.0,20.0000,-8750.0,No,01-01-2013,01-01-2013
46179,1993,Oldsmobile,Achieva,-1.0,24.0,-1.0,2200.0,Regular Gasoline,-1.0,26.0000,-1500.0,No,01-01-2013,01-01-2013
46180,1985,Dodge,B150/B250 Wagon 2WD,-1.0,15.0,-1.0,3550.0,Regular Gasoline,-1.0,17.0000,-8250.0,No,01-01-2013,01-01-2013
46182,1993,Pontiac,Grand Am,-1.0,21.0,-1.0,2550.0,Regular Gasoline,-1.0,22.0000,-3250.0,No,01-01-2013,01-01-2013
46184,1993,Subaru,Legacy,-1.0,22.0,-1.0,2400.0,Regular Gasoline,-1.0,24.0000,-2500.0,No,01-01-2013,01-01-2013

In [55]:
# Se cuentan la cantidad de datos con valor -1 en la columna 'CO2 (p/mile)'
conteo_valores_menos_uno = df_taxis_fuel['CO2 (p/mile)'].eq(-1).sum()

print(f"El nÃºmero de valores -1 en la columna 'CO2 (p/mile)' es: {conteo_valores_menos_uno}")

El nÃºmero de valores -1 en la columna 'CO2 (p/mile)' es: 28598

In [56]:
# Se filtra el DataFrame para ver solo las filas donde la columna 'CO2 (p/mile)' es -1
df_filtrado = df_taxis_fuel[df_taxis_fuel['CO2 (p/mile)'] == -1]

# Se muestra el DataFrame filtrado
df_filtrado

,Year,Manufacturer,Model,CO2 (p/mile),Miles per gallon (mpg),ef_x_comb,comb_x_year,Fuel,score_ghg,ef_x_comb_city,youSaveSpend,Alternative Fuel,createdOn,modifiedOn
7,1987,GMC,R15 Pickup 2WD,-1.0,15.0,-1.0,3550.0,Regular Gasoline,-1.0,17.0,-8250.0,No,01-01-2013,01-01-2013
16,1987,GMC,R15 Pickup 2WD,-1.0,19.0,-1.0,3100.0,Diesel,-1.0,22.0,-6000.0,No,01-01-2013,01-01-2013
21,1987,GMC,R25 Pickup 2WD,-1.0,15.0,-1.0,3550.0,Regular Gasoline,-1.0,17.0,-8250.0,No,01-01-2013,01-01-2013
27,1987,GMC,R25 Pickup 2WD,-1.0,14.0,-1.0,3800.0,Regular Gasoline,-1.0,15.0,-9500.0,No,01-01-2013,01-01-2013
34,1987,GMC,R25 Pickup 2WD,-1.0,17.0,-1.0,3450.0,Diesel,-1.0,19.0,-7750.0,No,01-01-2013,01-01-2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46177,1993,Mitsubishi,Diamante,-1.0,18.0,-1.0,3650.0,Premium Gasoline,-1.0,20.0,-8750.0,No,01-01-2013,01-01-2013
46179,1993,Oldsmobile,Achieva,-1.0,24.0,-1.0,2200.0,Regular Gasoline,-1.0,26.0,-1500.0,No,01-01-2013,01-01-2013
46180,1985,Dodge,B150/B250 Wagon 2WD,-1.0,15.0,-1.0,3550.0,Regular Gasoline,-1.0,17.0,-8250.0,No,01-01-2013,01-01-2013
46182,1993,Pontiac,Grand Am,-1.0,21.0,-1.0,2550.0,Regular Gasoline,-1.0,22.0,-3250.0,No,01-01-2013,01-01-2013
46184,1993,Subaru,Legacy,-1.0,22.0,-1.0,2400.0,Regular Gasoline,-1.0,24.0,-2500.0,No,01-01-2013,01-01-2013

In [57]:
# Se filtra el DataFrame para ver solo las filas donde la columna 'Fuel' es 'Electricity'
df_filtrado = df_taxis_fuel[df_taxis_fuel['Fuel'] == 'Electricity']

# Se muestra el DataFrame filtrado
df_filtrado

,Year,Manufacturer,Model,CO2 (p/mile),Miles per gallon (mpg),ef_x_comb,comb_x_year,Fuel,score_ghg,ef_x_comb_city,youSaveSpend,Alternative Fuel,createdOn,modifiedOn
20,2016,Tesla,Model S (75 kW-hr battery pack),0.0,98.0,10.0,700.0,Electricity,10.0,132.1,6000.0,No,04-05-2016,26-09-2016
187,2017,Kia,Soul Electric,0.0,105.0,10.0,650.0,Electricity,10.0,170.9,6250.0,No,13-09-2016,05-07-2017
239,2017,Hyundai,Ioniq Electric,0.0,136.0,10.0,500.0,Electricity,10.0,224.8,7000.0,No,16-11-2016,28-11-2017
261,2017,Ford,Focus Electric,0.0,107.0,10.0,650.0,Electricity,10.0,169.2,6250.0,No,16-12-2016,05-07-2017
268,2017,Tesla,Model S AWD - 60D,0.0,104.0,10.0,650.0,Electricity,10.0,137.5,6250.0,No,11-01-2017,02-02-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44945,2023,Audi,e-tron S (21/22 inch wheels),0.0,63.0,9.0,1100.0,Electricity,10.0,84.0,4000.0,No,17-05-2023,17-05-2023
44946,2023,Cadillac,LYRIQ AWD,0.0,89.0,10.0,800.0,Electricity,10.0,137.2,5500.0,No,17-05-2023,17-05-2023
44947,2023,Hyundai,Ioniq 6 Long range AWD (18 inch Wheels),0.0,121.0,10.0,600.0,Electricity,10.0,190.5,6500.0,No,17-05-2023,17-05-2023
44948,2023,Hyundai,Ioniq 6 Long range RWD (18 inch Wheels),0.0,140.0,10.0,500.0,Electricity,10.0,208.6,7000.0,No,17-05-2023,17-05-2023
44949,2023,Hyundai,Ioniq 6 Long range RWD (20 inch Wheels),0.0,117.0,10.0,600.0,Electricity,10.0,178.6,6500.0,No,17-05-2023,17-05-2023

In [58]:
# Se calcula el promedio de la columna "co2" sin contar los valores -1
promedio_co2 = df_taxis_fuel[df_taxis_fuel['CO2 (p/mile)'] != -1]['CO2 (p/mile)'].mean()
promedio_co2 = round(promedio_co2,2)
promedio_co2

391.58

In [59]:
# Se reemplaza los valores -1 por el promedio
df_taxis_fuel['CO2 (p/mile)'] = df_taxis_fuel['CO2 (p/mile)'].replace(-1, promedio_co2)
df_taxis_fuel

,Year,Manufacturer,Model,CO2 (p/mile),Miles per gallon (mpg),ef_x_comb,comb_x_year,Fuel,score_ghg,ef_x_comb_city,youSaveSpend,Alternative Fuel,createdOn,modifiedOn
0,2017,BMW,M6 Coupe,519.00,17.0,3.0,3850.0,Premium Gasoline,3.0,17.9989,-9750.0,No,04-04-2016,09-09-2016
1,2017,BMW,X3 sDrive28i,374.00,24.0,5.0,2700.0,Premium Gasoline,5.0,26.7866,-4000.0,No,04-04-2016,22-11-2016
2,2016,Infiniti,Q50S Red Sport,402.00,22.0,5.0,2950.0,Premium Gasoline,5.0,25.1000,-5250.0,No,04-04-2016,26-09-2016
3,2017,MINI,John Cooper Works Convertible,327.00,27.0,6.0,2400.0,Premium Gasoline,6.0,30.8534,-2500.0,No,12-04-2016,16-09-2016
4,2017,Kia,Sedona SX,433.00,21.0,4.0,2550.0,Regular Gasoline,4.0,22.8000,-3250.0,No,12-04-2016,02-12-2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46177,1993,Mitsubishi,Diamante,391.58,18.0,-1.0,3650.0,Premium Gasoline,-1.0,20.0000,-8750.0,No,01-01-2013,01-01-2013
46179,1993,Oldsmobile,Achieva,391.58,24.0,-1.0,2200.0,Regular Gasoline,-1.0,26.0000,-1500.0,No,01-01-2013,01-01-2013
46180,1985,Dodge,B150/B250 Wagon 2WD,391.58,15.0,-1.0,3550.0,Regular Gasoline,-1.0,17.0000,-8250.0,No,01-01-2013,01-01-2013
46182,1993,Pontiac,Grand Am,391.58,21.0,-1.0,2550.0,Regular Gasoline,-1.0,22.0000,-3250.0,No,01-01-2013,01-01-2013
46184,1993,Subaru,Legacy,391.58,22.0,-1.0,2400.0,Regular Gasoline,-1.0,24.0000,-2500.0,No,01-01-2013,01-01-2013

In [60]:
df_taxis_fuel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42813 entries, 0 to 46184
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    42813 non-null  int64
 1   Manufacturer            42813 non-null  object
 2   Model                   42813 non-null  object
 3   CO2 (p/mile)            42813 non-null  float64
 4   Miles per gallon (mpg)  42813 non-null  float64
 5   ef_x_comb               42813 non-null  float64
 6   comb_x_year             42813 non-null  float64
 7   Fuel                    42813 non-null  object
 8   score_ghg               42813 non-null  float64
 9   ef_x_comb_city          42215 non-null  float64
 10  youSaveSpend            42215 non-null  float64
 11  Alternative Fuel        42813 non-null  object
 12  createdOn               42193 non-null  object
 13  modifiedOn              42193 non-null  object
dtypes: float64(7), int64(1), object(6)
memory usage: 4.9+ MB